### ISSUE TITLE
The text: Remove Dark mode ads and more from above other texts.

### ISSUE THREAD

**Issue by SMOKESCREE** [illogical-robot/apkmirror-public#274] opened 2024-01-28 17:39 UTC
The text:
Remove Dark mode ads and more from above other texts.
![20240128173329](https://github.com/illogical-robot/apkmirror-public/assets/79532295/30874919-f725-4f01-ab44-29f878beaa0f)

**Comment by archon810** [comment] 2024-01-28 17:45
I'm not seeing any ads on your screen, are you using an ad blocker? Ad blockers mangle UIs and are unsupported.

**Comment by archon810** [comment] 2024-03-28 23:35
I verified the issue if you're using an ad blocker on the site in Brave. The issue goes away if no ad blocker is used. Closing as wontfix as it's working as intended without the ad blocker.

**Closed by archon810** 2024-03-28 23:35 UTC
